In [1]:
# Import dependencies
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [3]:
# Read csv file
train_df = pd.read_csv("Resources/TrainingWiDS2021.csv")
train_df

,Unnamed: 0,encounter_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,hospital_admit_source,...,h1_pao2fio2ratio_max,h1_pao2fio2ratio_min,aids,cirrhosis,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,diabetes_mellitus
0,1,214826,118,68.0,22.732803,0,Caucasian,M,180.3,Floor,...,NaN,NaN,0,0,0,0,0,0,0,1
1,2,246060,81,77.0,27.421875,0,Caucasian,F,160.0,Floor,...,51.0,51.0,0,0,0,0,0,0,0,1
2,3,276985,118,25.0,31.952749,0,Caucasian,F,172.7,Emergency Department,...,NaN,NaN,0,0,0,0,0,0,0,0
3,4,262220,118,81.0,22.635548,1,Caucasian,F,165.1,Operating Room,...,337.0,337.0,0,0,0,0,0,0,0,0
4,5,201746,33,19.0,NaN,0,Caucasian,M,188.0,NaN,...,NaN,NaN,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130152,130153,164758,7,50.0,29.287256,0,Caucasian,M,175.3,Emergency Department,...,NaN,NaN,0,0,0,0,0,0,0,0
130153,130154,197653,7,79.0,29.653433,0,Caucasian,F,162.6,Direct Admit,...,NaN,NaN,0,0,0,0,0,0,0,0
130154,130155,219719,7,73.0,32.265371,0,African American,M,177.8,Emergency Department,...,163.0,163.0,0,0,0,0,0,0,0,1
130155,130156,222562,170,81.0,24.408579,0,Caucasian,M,185.4,Emergency Department,...,NaN,NaN,0,0,0,0,0,0,0,0
130156,130157,157942,7,35.0,30.132358,0,African American,M,182.9,Emergency Department,...,NaN,NaN,0,0,0,0,0,0,0,0

In [12]:
# Use columns 'age', 'bmi', 'ethnicity', 'gender' and 'diabetes_mellitus' to predict diabetes mellitus
train_sample = train_df[['age', 'bmi', 'ethnicity', 'gender', 'diabetes_mellitus']]
train_sample

         age        bmi         ethnicity gender  diabetes_mellitus
0       68.0  22.732803         Caucasian      M                  1
1       77.0  27.421875         Caucasian      F                  1
2       25.0  31.952749         Caucasian      F                  0
3       81.0  22.635548         Caucasian      F                  0
4       19.0        NaN         Caucasian      M                  0
...      ...        ...               ...    ...                ...
130152  50.0  29.287256         Caucasian      M                  0
130153  79.0  29.653433         Caucasian      F                  0
130154  73.0  32.265371  African American      M                  1
130155  81.0  24.408579         Caucasian      M                  0
130156  35.0  30.132358  African American      M                  0

[130157 rows x 5 columns]

In [13]:
train_sample.isnull().sum()

age                  4988
bmi                  4490
ethnicity            1587
gender                 66
diabetes_mellitus       0
dtype: int64

In [14]:
# use X as features and y as target 
X = train_sample.drop(columns="diabetes_mellitus")
y = train_sample["diabetes_mellitus"]

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)
X_train.shape

(97617, 4)